paths:
  /mediamtx-auth:
    post:
      security:
        - apikeyAuth: []
      parameters:
        - in: body
          name: body
          schema:
            type: object
      responses:
        200:
          description: Success
          schema:
            type: object

  /mediamtx-get-recording:
    post:
      security:
        - basicAuth: []
      parameters:
        - in: body
          name: body
          schema:
            type: object
      responses:
        200:
          description: Success
          schema:
            type: object

  /mediamtx-get-path:
    post:
      security:
        - basicAuth: []
      parameters:
        - in: body
          name: body
          schema:
            type: object
      responses:
        200:
          description: Success
          schema:
            type: object

  /mediamtx-get-media:
    post:
      security:
        - basicAuth: []
      parameters:
        - in: body
          name: body
          schema:
            type: object
      responses:
        200:
          description: Success
          schema:
            type: object

  /mediamtx-add-media:
    post:
      security:
        - basicAuth: []
      parameters:
        - in: body
          name: body
          schema:
            type: object
      responses:
        200:
          description: Success
          schema:
            type: object

  /mediamtx-delete-media:
    post:
      security:
        - basicAuth: []
      parameters:
        - in: body
          name: body
          schema:
            type: object
      responses:
        200:
          description: Success
          schema:
            type: object
